# Generated by Django 6.1 on 2026-08-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=60, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('picture_happy', models.ImageField(upload_to='')),
                ('picture_sad', models.ImageField(upload_to='')),
                ('party_code', models.CharField(max_length=5, null=True)),
                ('party', models.CharField(max_length=40)),
                ('description', models.TextField(null=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.classname')),
            ],
        ),
    ]
