# Generated by Django 6.1 on 2026-08-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('parti', models.CharField(blank=True, max_length=100)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
    ]
