# Generated by Django 6.1 on 2026-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='picture_neutral',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_happy',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_sad',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
