# Generated by Django 6.1 on 2026-08-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_candidate_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='class_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_vote', to='vote.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='global_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_vote', to='vote.candidate'),
        ),
    ]
