# Generated by Django 6.1 on 2026-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_candidate_picture_neutral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_happy',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_neutral',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='picture_sad',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
