# Generated by Django 6.1 on 2026-08-25 13:32

import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=10, primary_key=True, serialize=False),
        ),
    ]
