# Generated by Django 6.1 on 2026-08-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='OE2qZ56hPS', max_length=10, primary_key=True, serialize=False),
        ),
    ]
