# Generated by Django 6.1 on 2026-08-25 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_alter_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ClassName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.classname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='UmGhXl430F', max_length=10, primary_key=True, serialize=False),
        ),
    ]
